### ISSUE TITLE
Vision based Tiny VLM

### ISSUE THREAD

**Issue by abhigoku10** [YuchuanTian/RethinkTinyLM#2]
@YuchuanTian  thanks sharing ur wonderful work just had one query , can use ur method or technique for even vision based LLM ? if so can u share some reference 
THanks in advance

**Comment by YuchuanTian** [comment]
Yes, our methods potentially work on vision LLMs in principle, but our major focus is on language LLMs. In this study, we haven't investigated vision LLMs in detail.
