### ISSUE TITLE
如何实现难样本挖掘？

### ISSUE THREAD

**Issue by LinB203** [YuchuanTian/RethinkTinyLM#3]
如何实现筛选出第一个epoch的loss较大的50%的样本？然后继续第二个epoch训练？有示例代码参考嘛？

**Comment by LinB203** [comment]
@YuchuanTian

**Comment by YuchuanTian** [comment]
We have updated README.md to include the training details (please refer to the "Multiple-Round Training" section). Thanks for reaching out!
